apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-controller
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-controller
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-controller
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "{{ .Values.metricsPort }}"
      #   prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: controller
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: {{ .Values.servicename }}-controller
        image: "{{ .Values.docker.GeneralFullImagePreamble }}{{ .Values.dimage }}:{{ .Values.tagversion }}"
        command: ["/usr/bin/controller"]
        ports:
          - containerPort: {{ .Values.componentPorts.controller }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/fledge/controller.yaml
            subPath: controller.yaml
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fledge-s3-iam
                key: AWS_ACCESS_KEY_ID
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: fledge-s3-iam
                key: AWS_DEFAULT_REGION
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fledge-s3-iam
                key: AWS_SECRET_ACCESS_KEY
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-controller-configmap
        {{- if .Values.mongodbcredentials }}
        - name: {{ .Release.Name }}-mongodb
          secret:
            secretName: {{ .Release.Name }}-mongodb
        {{- end }}