# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
"""Loads real-profiled vclock charges for sim-only costs sim can't measure
live (FWDLLM_DESIGN.md §P). One YAML per dispatch family, regenerated by
`expt_scripts/profile_sim_charges.py` -- never hand-type the numbers, only
the `charge:` flag is a human decision."""

import functools
import logging

import yaml

logger = logging.getLogger(__name__)


@functools.lru_cache(maxsize=8)
def _load(path: str) -> dict:
    try:
        with open(path) as f:
            return yaml.safe_load(f) or {}
    except OSError as e:
        logger.warning(f"[SIM_CHARGE_PROFILE] failed to load {path}: {e}")
        return {}


def get_profiled_charge_s(
    path: str | None, label: str, payload_kind: str | None = None
) -> float | None:
    """Mean charge (s) for `label`/`payload_kind` if the registry at `path`
    marks it `charge: true`, else None -- caller falls back to its existing
    behavior (no profiled charge). `path=None` (no registry configured) is
    always a no-op, so this is inert unless a baseline's yaml opts in."""
    if not path:
        return None
    entry = _load(path).get(label, {}).get(payload_kind or "_default")
    if not entry or not entry.get("charge"):
        return None
    return float(entry["mean_s"])
